import { adminDb, requireUser, requireStaff } from '../_lib/supabase.js';
import { assertMethod, sendJson } from '../_lib/http.js';
const METHODS = new Set(['cash_at_counter','upi','razorpay','stripe']);
const STATUSES = { pending:['accepted','cancelled'], accepted:['preparing','cancelled'], preparing:['ready_for_pickup','cancelled'], ready_for_pickup:['completed','cancelled'], completed:[], cancelled:[], refunded:[] };
export function fail(res, status, code, message) { return sendJson(res,status,{error:{code,message}}); }
export function publicOrder(order) { return { orderNumber:order.order_number,customerName:order.customer_name,phone:order.phone,pickupToken:order.pickup_token,subtotal:order.subtotal,tax:order.tax,total:order.total,paymentMethod:order.payment_method,paymentStatus:order.payment_status,orderStatus:order.order_status,createdAt:order.created_at,completedAt:order.completed_at,items:order.order_items?.map(i=>({productId:i.product_id,name:i.product_name,quantity:i.quantity,unitPrice:i.unit_price,lineTotal:i.line_total}))||[] }; }
export async function actor(req, staff=false) { return staff ? requireStaff(req) : requireUser(req); }
export async function listOrders(user, staff, query={}) { let request=adminDb.from('orders').select('order_number,pickup_token,subtotal,tax,total,payment_method,payment_status,order_status,created_at,completed_at,user_id,customer_name,phone,order_items(product_id,product_name,quantity,unit_price,line_total)',{count:'exact'}).order('created_at',{ascending:false}); if(!staff) request=request.eq('user_id',user.id); if(query.status) request=request.eq('order_status',query.status); const page=Math.max(1,Number(query.page)||1), size=Math.min(100,Math.max(1,Number(query.pageSize)||25)); const {data,error,count}=await request.range((page-1)*size,page*size-1); if(error) throw error; return {orders:data.map(publicOrder),pagination:{page,pageSize:size,total:count||0}}; }
export async function loadOrder(user, staff, number) { const {data,error}=await adminDb.from('orders').select('id,order_number,pickup_token,subtotal,tax,total,payment_method,payment_status,order_status,created_at,completed_at,user_id,customer_name,phone,order_items(product_id,product_name,quantity,unit_price,line_total)').eq('order_number',number).single(); if(error||!data) return null; if(!staff && data.user_id!==user.id) return null; return data; }
export async function audit(actorId, action, order, metadata={}) { await adminDb.from('audit_logs').insert({actor_id:actorId,action,entity_type:'order',entity_id:order.id,metadata:{order_number:order.order_number,...metadata}}); }
export async function updateStatus(user, order, status) { if(!STATUSES[order.order_status]?.includes(status)) { const e=new Error('Invalid status transition'); e.status=409; throw e; } const values={order_status:status}; if(status==='completed') values.completed_at=new Date().toISOString(); const {data,error}=await adminDb.from('orders').update(values).eq('id',order.id).select().single(); if(error) throw error; await audit(user.id,'order.status_changed',order,{from:order.order_status,to:status}); return data; }
