-- Production schema: apply in a new Supabase project before enabling the application.
create extension if not exists pgcrypto;
create type public.app_role as enum ('customer','staff','admin');
create type public.order_status as enum ('pending','accepted','preparing','ready_for_pickup','completed','cancelled','refunded');
create type public.payment_status as enum ('pending','paid','failed','refunded');

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text not null check (char_length(full_name) between 1 and 100), email text not null, phone text, role public.app_role not null default 'customer', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.categories (id uuid primary key default gen_random_uuid(), name text not null unique, slug text not null unique, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.products (id uuid primary key default gen_random_uuid(), category_id uuid references public.categories(id) on delete set null, name text not null, description text, price numeric(10,2) not null check(price >= 0), available boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.product_images (id uuid primary key default gen_random_uuid(), product_id uuid not null references public.products(id) on delete cascade, storage_path text not null, alt_text text, sort_order int not null default 0 check(sort_order >= 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create sequence public.order_number_sequence start 1;
create table public.orders (id uuid primary key default gen_random_uuid(), order_number text not null unique default ('CAFE-' || lpad(nextval('public.order_number_sequence')::text, 6, '0')), user_id uuid not null references public.profiles(id), customer_name text not null, email text not null, phone text, subtotal numeric(10,2) not null check(subtotal >= 0), tax numeric(10,2) not null default 0 check(tax >= 0), total numeric(10,2) not null check(total >= 0), payment_method text not null check(payment_method in ('cash_at_counter','upi','razorpay','stripe')), payment_status public.payment_status not null default 'pending', order_status public.order_status not null default 'pending', pickup_token text not null unique default upper(substr(encode(gen_random_bytes(8),'hex'),1,10)), completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.order_items (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, product_id uuid references public.products(id) on delete set null, product_name text not null, unit_price numeric(10,2) not null check(unit_price >= 0), quantity int not null check(quantity > 0), line_total numeric(10,2) not null check(line_total >= 0), created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.payments (id uuid primary key default gen_random_uuid(), order_id uuid not null references public.orders(id) on delete cascade, gateway text not null, transaction_id text unique, amount numeric(10,2) not null check(amount >= 0), status public.payment_status not null default 'pending', refund_status text, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id) on delete set null, order_id uuid references public.orders(id) on delete cascade, channel text not null, event text not null, status text not null default 'queued', sent_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.audit_logs (id uuid primary key default gen_random_uuid(), actor_id uuid references public.profiles(id) on delete set null, action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}', created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.settings (id uuid primary key default gen_random_uuid(), key text not null unique, value jsonb not null, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create table public.staff (id uuid primary key default gen_random_uuid(), user_id uuid not null unique references public.profiles(id) on delete cascade, employee_code text unique, active boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index orders_user_created_idx on public.orders(user_id, created_at desc); create index orders_status_created_idx on public.orders(order_status, created_at desc); create index order_items_order_idx on public.order_items(order_id); create index products_category_idx on public.products(category_id);
create or replace function public.set_updated_at() returns trigger language plpgsql as $$ begin new.updated_at = now(); return new; end $$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path = public as $$ begin insert into public.profiles(id,full_name,email,phone) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','Customer'),new.email,new.raw_user_meta_data->>'phone'); return new; end $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create trigger profiles_updated before update on public.profiles for each row execute procedure public.set_updated_at();
create trigger orders_updated before update on public.orders for each row execute procedure public.set_updated_at();
create or replace function public.is_staff() returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.profiles where id=auth.uid() and role in ('staff','admin')) $$;
alter table public.profiles enable row level security; alter table public.categories enable row level security; alter table public.products enable row level security; alter table public.product_images enable row level security; alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.payments enable row level security; alter table public.notifications enable row level security; alter table public.audit_logs enable row level security; alter table public.settings enable row level security; alter table public.staff enable row level security;
create policy profiles_self on public.profiles for select using (id=auth.uid() or public.is_staff()); create policy profiles_update_self on public.profiles for update using (id=auth.uid()) with check (id=auth.uid());
create policy menu_read on public.categories for select using (true); create policy products_read on public.products for select using (available or public.is_staff()); create policy images_read on public.product_images for select using (true);
create policy orders_self_or_staff on public.orders for select using (user_id=auth.uid() or public.is_staff()); create policy items_self_or_staff on public.order_items for select using (exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or public.is_staff()))); create policy payments_self_or_staff on public.payments for select using (exists(select 1 from public.orders o where o.id=order_id and (o.user_id=auth.uid() or public.is_staff())));
create policy notification_self_or_staff on public.notifications for select using (user_id=auth.uid() or public.is_staff());
-- Product/category writes, order creation and status changes occur only through Vercel functions using the service-role key.
alter publication supabase_realtime add table public.orders;
